services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=paso
    volumes:
      - ./dataPG:/var/lib/postgresql/data
  odoo:
    image: odoo:16
    container_name: odoo_16
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=paso
    ports:
      - '8069:8069'
    volumes:
      - ./volumesOdoo/addons:/mnt/extra-addons
      - ./volumesOdoo/filestore:/var/lib/odoo/filestore
    depends_on:
      - postgres
    command: --dev=all
